name: 'Check All GitHub Actions for Security Issues via bin3xish477 ASA'
on:
  push:
jobs:
  RunAsa:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3

    - name: Dynamic Security Testing
      uses: projectdiscovery/nuclei-action@main
      with:
        target: http://app.cheapcryptobank.com
