name: ZAP DAST Scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
        with:
          fetch-depth: 0
      - name: ZAP Scan
        #uses: zaproxy/action-full-scan@eceb20949194c4d2be3c72cd1bbc6b645e41509d # 0.5.1
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://app.cheapcryptobank.com/'
